"""
Netscape Cookie Format Converter
Provides utilities to parse and save cookies in Netscape format.
"""

from typing import List, Dict
import logging

logger = logging.getLogger(__name__)


def parse_netscape_cookies(file_path: str) -> List[Dict]:
    """
    Parse Netscape format cookie file and return Playwright cookie list.

    Netscape format:
    domain    flag    path    secure    expiration    name    value

    Args:
        file_path: Path to the Netscape cookie file

    Returns:
        List of cookie dictionaries compatible with Playwright

    Raises:
        FileNotFoundError: If cookie file doesn't exist
        ValueError: If cookie format is invalid
    """
    cookies = []

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            for line_num, line in enumerate(f, 1):
                # Skip comments and empty lines
                line = line.strip()
                if not line or line.startswith('#'):
                    continue

                # Parse cookie line
                parts = line.split('\t')
                if len(parts) != 7:
                    logger.warning(f"Line {line_num}: Invalid format, expected 7 fields, got {len(parts)}")
                    continue

                domain, flag, path, secure, expiration, name, value = parts

                # Convert to Playwright format
                cookie = {
                    "name": name,
                    "value": value,
                    "domain": domain,
                    "path": path,
                    "secure": secure.upper() == "TRUE",
                    "httpOnly": False,  # Netscape format doesn't include httpOnly
                    "sameSite": "Lax"   # Default to Lax for compatibility
                }

                # Add expiration if valid
                try:
                    expires = int(expiration)
                    if expires > 0:
                        cookie["expires"] = expires
                except ValueError:
                    logger.warning(f"Line {line_num}: Invalid expiration value '{expiration}'")

                cookies.append(cookie)
                logger.debug(f"Parsed cookie: {name} for domain {domain}")

        logger.info(f"Successfully parsed {len(cookies)} cookies from {file_path}")
        return cookies

    except FileNotFoundError:
        logger.error(f"Cookie file not found: {file_path}")
        raise
    except Exception as e:
        logger.error(f"Error parsing cookie file: {e}")
        raise


def save_netscape_cookies(cookies: List[Dict], file_path: str):
    """
    Save Playwright cookies to Netscape format file.

    Args:
        cookies: List of Playwright cookie dictionaries
        file_path: Path to save the cookie file

    Raises:
        IOError: If unable to write to file
    """
    try:
        with open(file_path, 'w', encoding='utf-8') as f:
            # Write header
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# https://curl.se/docs/http-cookies.html\n")
            f.write("# This file was generated by cookie-refresher\n\n")

            # Write cookies
            for cookie in cookies:
                domain = cookie.get('domain', '')
                # Flag indicates if domain starts with dot (for all subdomains)
                flag = "TRUE" if domain.startswith('.') else "FALSE"
                path = cookie.get('path', '/')
                secure = "TRUE" if cookie.get('secure', False) else "FALSE"

                # Expiration: use expires if available, otherwise set to 0 (session cookie)
                expires = cookie.get('expires', 0)
                if isinstance(expires, float):
                    expires = int(expires)

                name = cookie.get('name', '')
                value = cookie.get('value', '')

                # Write in Netscape format: domain\tflag\tpath\tsecure\texpiration\tname\tvalue
                line = f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
                f.write(line)
                logger.debug(f"Saved cookie: {name} for domain {domain}")

        logger.info(f"Successfully saved {len(cookies)} cookies to {file_path}")

    except IOError as e:
        logger.error(f"Error writing cookie file: {e}")
        raise
    except Exception as e:
        logger.error(f"Unexpected error saving cookies: {e}")
        raise
